project:
  type: website
  output-dir: docs

website:
  title: "1990s vs 2020s R&B: Danceable vs Atmospheric Music"
  navbar:
    left:
      - href: index.qmd
        text: Background & Corpus
      - href: track-level.qmd
        text: Track-level Features
      - href: timbre.qmd
        text: Timbre Features
      - href: temporal.qmd
        text: Temporal Features
      - href: clustering&classification.qmd
        text: Clustering & Classification
      - href: conclusion.qmd
        text: Conclusion

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-location: left
    smooth-scroll: true
    number-sections: false
    code-fold: true
    code-summary: "Show code"